-- Capture: "On Liberal Nationalism" (Nitin Pai) -> in-app reader for reading pp221_lu01_m02.
-- Pure-ASCII (non-ASCII chars entity-encoded), dollar-quoted HTML. Paste into Supabase SQL Editor and Run.
insert into public.reading_content (url, reading_id, title, kind, content_html, extracted_by)
values (
  'https://www.nitinpai.in/2008/09/04/on-liberal-nationalism',
  'pp221_lu01_m02',
  'On Liberal Nationalism',
  'article',
  $rc$<p><em>Connecting liberalism, nationalism and realism</em></p>
<p>Let&#8217;s start with an axiom: all individuals are free, and from this freedom, they possess certain inalienable rights. They possess these rights and freedoms at all times, but in a state of nature, their ability to enjoy the freedom and exercise the rights is circumscribed by their individual power. In Indian philosophy, the state of nature is termed as <em>matsya nyaya</em>, or the law of the fishes, a condition under which the stronger fish eats the weaker fish. Thomas Hobbes, the 17th century English philosopher, <a href="https://en.wikipedia.org/wiki/Thomas_Hobbes" target="_blank">describes</a> this as the time when<span class="push-double"></span> <span class="pull-double">&#8220;</span>men live without a common power to keep them all in awe, they are in that condition which is called war; and such a war as is of every man against every man (<em>bellum omnium contra omnes</em>).&#8221; Life, therefore, is<span class="push-double"></span> <span class="pull-double">&#8220;</span>solitary, poor, nasty, brutish, and short.&#8221;</p>
<p>To better enjoy their rights and freedoms, individuals trade-off a part of their freedom for the security offered by a state. Hence Kautilya writes</p>
<blockquote>
<p>People suffering from anarchy as illustrated by the proverbial tendency of a large fish swallowing a small one (<em>matsyanyayabhibhutah prajah</em>), first elected Manu, the Vaivasvata, to be their king; and allotted one-sixth of the grains grown and one-tenth of merchandise as sovereign dues. Fed by this payment, kings took upon themselves the responsibility of maintaining the safety and security of their subjects (<em>yogakshemavah</em>), and of being answerable for the sins of their subjects when the principle of levying just punishments and taxes has been violated.[<a href="http://www.mssu.edu/projectsouthasia/history/primarydocs/Arthashastra/BookI.htm" target="_blank">Arthashastra I:13</a>]</p>
</blockquote>
<p>In Western philosophy, this trade-off forms the basis of <a href="https://en.wikipedia.org/wiki/Social_contract" target="_blank">social contract</a> theories. In <em>Leviathan</em>, Hobbes argues that individuals cede all their rights in return for protection to a sovereign who is himself above the law. John Locke, writing after Hobbes, is more moderate: in his view, individuals surrender only <em>some</em> of their rights to a government that rules by the consent of the governed.</p>
<p>This trade-off forms the basis of modern liberal democratic states. The exact implementation differs from state to state, and depends on a number of factors. But most often, the social contract is codified in a constitution. Constitutions are not, and do not have to be either perfect or immutable. To varying degrees, they affirm the rights of the individual and offer an enlightened method to settle the differences between the interests of individuals. In sharp contrast to Hobbes&#8217; <em>Leviathan</em>, modern constitutions also, to varying degrees, make the government itself subject to the rule of law.</p>
<p>The upshot is that the state is <em>necessary</em> for the practical enjoyment of individual rights and freedoms. The survival and security of the state&#8212;often termed<span class="push-double"></span> <span class="pull-double">&#8220;</span>the national interest&#8221;&#8212;is directly connected to the ability of citizens to enjoy their freedom. Put <a href="https://www.nitinpai.in/2008/07/20/reading-the-arthashastra-sovereignty-power-and-happiness/">in another way</a>, the<span class="push-double"></span> <span class="pull-double">&#8220;</span>national interest&#8221; is the well-being and development of all its citizens.</p>
<p>If we adopt this people-centric definition of the national interest, how should one regard territory? Is territorial integrity uncompromisable? Not quite. To the extent territory is necessary for the well-being and development of <em>all</em> citizens, holding the territory is in the national interest. Where territorial compromises enhance the well-being of citizens, they are in the national interest. In the state-centric formulation, the objective question is whether acquiring, keeping or parting with a particular piece of land enhances the survival and security of the state, or not.</p>
<p>While the establishment of a state allows individuals to enjoy their rights&#8212;abridged as they are&#8212;the relationship between states remains in the world of <em>matsya nyaya</em> or anarchy. To an extent, the development of international law and institutions like the United Nations allow states to pursue<span class="push-single"></span> <span class="pull-single">&#8216;</span>rules-based&#8217; relations. But the ultimate arbiter of international relations is power. It follows that to protect its national interests&#8212;whether expressed in the people-centric or state-centric terms&#8212;states have to maximise their power relative to others. This results in an international balance-of-power, which can be stable or unstable depending on the power dynamics obtaining at a particular moment in time. The objective of the state then, is to maximise its own power to ensure that the international balance-of-power is in its favour.</p>
<p>This is how liberalism, nationalism and realism are connected with each other. Liberalism (or libertarianism, in its American usage) is concerned about individual freedom. To enjoy freedom in practice, the individual gives up some of it to the state. The state, a nation-state in India&#8217;s case, exists to ensure the rights, freedoms and well-being (<em>yogakshema</em>) of its people. So ensuring the survival and security of the Indian state&#8212;by maximising its relative power internationally&#8212;is wholly consistent with allowing its citizens to live in freedom.</p>$rc$,
  'readability'
)
on conflict (url) do update set
  reading_id = excluded.reading_id,
  title      = excluded.title,
  kind       = excluded.kind,
  content_html = excluded.content_html,
  extracted_by = excluded.extracted_by;
